#!/bin/bash

# run this script as a user who has sudo access
# the command line argument is the user to set up mapmill for

set -e
if [ "$#" -ne 1 ]; then
    echo "usage: setup [user]"
    exit
fi

user=$1

if ! id -u $user >& /dev/null; then
    echo "user $user does not exist"
    exit
fi


# install packages
sudo echo
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install -y emacs24
sudo apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
sudo apt-get install -y libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
sudo apt-get install -y mysql-server mysql-client libmysqlclient-dev

sudo apt-get install -y nodejs
sudo npm install -g bower


# install ruby / rails
sudo su -l $user <<EOF
set -e
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install 2.1.5
rvm use 2.1.5 --default
ruby -v

echo "gem: --no-ri --no-rdoc" > ~/.gemrc
gem install bundler

gem install rails -v 4.1.8
rails -v
EOF


# setup mapmill
sudo su -l $user <<EOF
set -e
git clone https://github.com/scoopergit/mapmill
cd mapmill
bundle install
bower install
cp config/database.yml.sqlite3 config/database.yml
cp config/app_environment_vars.rb.s3sample config/app_environment_vars.rb
rake db:create
rake db:migrate
EOF


# setup fakes3
sudo su -l $user <<EOF
set -e
mkdir fake-s3-root
git clone https://github.com/scoopergit/fake-s3.git
cd fake-s3
gem build fakes3.gemspec
gem install fakes3-0.1.7.gem
EOF


# display information
echo
echo
echo
echo ==========
echo Edit: config/app_environment_vars.rb
echo Run: fakes3 -p [port] -r [root folder] -o [allowed origin]
echo Run: thin start -p [port] --ssl --ssl-key-file [key file] --ssl-cert-file [cert file]
