#!/bin/bash --login

# For usage run:
#   ./setup

set -e

if ! shopt -q login_shell; then
   echo "must be run as login shell"
   exit
fi


if [ "$1" == "system" ]; then
    # install packages
    sudo echo -n
    sudo add-apt-repository -y ppa:chris-lea/node.js
    sudo apt-get update
    sudo apt-get install -y emacs24
    sudo apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
    sudo apt-get install -y libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
    sudo apt-get install -y mysql-server mysql-client libmysqlclient-dev
    sudo apt-get install -y gawk
    
    sudo apt-get install -y nodejs
    sudo npm install -g bower


elif [ "$1" == "user" ]; then
    # install ruby / rails
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    curl -L https://get.rvm.io | bash -s stable
    source ~/.rvm/scripts/rvm
    rvm autolibs fail
    rvm install 2.1.5
    rvm use 2.1.5 --default
    ruby -v

    echo "gem: --no-ri --no-rdoc" > ~/.gemrc
    gem install bundler

    gem install rails -v 4.1.8
    rails -v


    # setup mapmill
    git clone https://github.com/scoopergit/mapmill
    cd mapmill
    bundle install
    bower install
    cp config/database.yml.sqlite3 config/database.yml
    cp config/app_environment_vars.rb.s3sample config/app_environment_vars.rb
    rake db:create
    rake db:migrate
    cd -


    # setup fakes3
    mkdir fake-s3-root
    git clone https://github.com/scoopergit/fake-s3.git
    cd fake-s3
    gem build fakes3.gemspec
    gem install fakes3-0.1.7.gem
    cd -


    # display information
    echo
    echo
    echo
    echo ==========
    echo Edit: config/app_environment_vars.rb
    echo Run: fakes3 -p [port] -r [root folder] -o [allowed origin]
    echo Run: thin start -p [port] --ssl --ssl-key-file [key file] --ssl-cert-file [cert file]
    echo
    echo Note: ruby and rvm commands must be run in a login shell


else
    echo "usage:"
    echo
    echo "  For system setup run as a user with sudo access:"
    echo "    ./setup system"
    echo
    echo "  For user setup run:"
    echo "    ./setup user"

fi
